// <auto-generated />
using System;
using FloodRescue.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FloodRescue.Repositories.Migrations
{
    [DbContext(typeof(FloodRescueDbContext))]
    [Migration("20260126171103_Fix_User")]
    partial class Fix_User
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FloodRescue.Repositories.Entites.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CategoryName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT")
                        .HasColumnName("IsDeleted");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.CitizenNotification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NotificationID");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedTime");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Message");

                    b.Property<Guid>("RescueRequestID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RescueRequestID");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Title");

                    b.HasKey("NotificationID");

                    b.HasIndex("RescueRequestID");

                    b.ToTable("CitizenNotification");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.IncidentReport", b =>
                {
                    b.Property<Guid>("IncidentReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("IncidentReportID");

                    b.Property<string>("CoordinatorNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CoordinatorNote");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedTime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<double>("Latitiude")
                        .HasColumnType("float")
                        .HasColumnName("Latitiude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("Longitude");

                    b.Property<Guid>("ReportedID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReportedID");

                    b.Property<Guid>("RescueMissionID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RescueMissionID");

                    b.Property<Guid>("ResolvedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ResolvedBy");

                    b.Property<DateTime?>("ResolvedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ResolvedTime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Title");

                    b.HasKey("IncidentReportID");

                    b.HasIndex("ReportedID");

                    b.HasIndex("RescueMissionID");

                    b.HasIndex("ResolvedBy");

                    b.ToTable("IncidentReports");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.Inventory", b =>
                {
                    b.Property<Guid>("InventoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("InventoryID");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastUpdated");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<int>("ReliefItemID")
                        .HasColumnType("int")
                        .HasColumnName("ReliefItemID");

                    b.Property<int>("WarehouseID")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.HasKey("InventoryID");

                    b.HasIndex("ReliefItemID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.Notification", b =>
                {
                    b.Property<Guid>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("NotificationID");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedTime");

                    b.Property<bool>("IsRead")
                        .HasColumnType("BIT")
                        .HasColumnName("IsRead");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Message");

                    b.Property<Guid?>("ReferenceID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReferenceID");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Title");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.HasKey("NotificationID");

                    b.HasIndex("UserID");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.RefreshToken", b =>
                {
                    b.Property<int>("RefresTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RefresTokenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefresTokenID"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiredAt");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit")
                        .HasColumnName("IsRevoked");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("IsUsed");

                    b.Property<string>("JwtID")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("JwtID");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("Token");

                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.HasKey("RefresTokenID");

                    b.HasIndex("UserID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.ReliefItem", b =>
                {
                    b.Property<int>("ReliefItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReliefItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReliefItemID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("ReliefItemName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ReliefItemName");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Unit");

                    b.HasKey("ReliefItemID");

                    b.HasIndex("CategoryID");

                    b.ToTable("ReliefItems");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.ReliefOrder", b =>
                {
                    b.Property<Guid>("ReliefOrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReliefOrderID");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedTime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("ManagerID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ManagerID");

                    b.Property<DateTime?>("PreparedTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("PreparedTime");

                    b.Property<Guid>("RescueRequestID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RescueRequestID");

                    b.Property<Guid?>("RescueTeamID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RescueTeamID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Status");

                    b.Property<int>("WarehouseID")
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    b.HasKey("ReliefOrderID");

                    b.HasIndex("ManagerID");

                    b.HasIndex("RescueRequestID");

                    b.HasIndex("RescueTeamID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("ReliefOrders");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.ReliefOrderDetail", b =>
                {
                    b.Property<Guid>("ReliefOrderDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReliefOrderDetailID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("Quantity");

                    b.Property<int>("ReliefItemID")
                        .HasColumnType("int")
                        .HasColumnName("ReliefItemID");

                    b.Property<Guid>("ReliefOrderID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ReliefOrderID");

                    b.HasKey("ReliefOrderDetailID");

                    b.HasIndex("ReliefItemID");

                    b.HasIndex("ReliefOrderID");

                    b.ToTable("ReliefOrderDetails");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.RescueMission", b =>
                {
                    b.Property<Guid>("RescueMissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RescueMissionID");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("AssignedAt");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("EndTime");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid>("RescueRequestID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RescueRequestID");

                    b.Property<Guid>("RescueTeamID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RescueTeamID");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("StartTime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Status");

                    b.HasKey("RescueMissionID");

                    b.HasIndex("RescueRequestID");

                    b.HasIndex("RescueTeamID");

                    b.ToTable("RescueMissions");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.RescueRequest", b =>
                {
                    b.Property<Guid>("RescueRequestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RescueRequestID");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(225)")
                        .HasColumnName("Address");

                    b.Property<string>("CitizenName")
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("CitizenName");

                    b.Property<string>("CitizenPhone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("CitizenPhone");

                    b.Property<Guid?>("CoordinatorID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CoordinatorID");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2(7)")
                        .HasColumnName("CreatedTime");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT")
                        .HasColumnName("IsDeleted");

                    b.Property<double>("LocationLatitude")
                        .HasColumnType("float")
                        .HasColumnName("LocationLatitude");

                    b.Property<double>("LocationLongitude")
                        .HasColumnType("float")
                        .HasColumnName("LocationLongitude");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("int")
                        .HasColumnName("PeopleCount");

                    b.Property<string>("RejectedNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("RejectedNote");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("RequestType");

                    b.Property<string>("ShortCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("ShortCode");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Status");

                    b.HasKey("RescueRequestID");

                    b.HasIndex("CoordinatorID");

                    b.HasIndex("ShortCode")
                        .IsUnique();

                    b.ToTable("RescueRequests");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.RescueRequestImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ImageUrl");

                    b.Property<Guid>("RescueRequestID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RescueRequestID");

                    b.Property<Guid?>("RescueTeamID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImageId");

                    b.HasIndex("RescueRequestID");

                    b.HasIndex("RescueTeamID");

                    b.ToTable("RescueRequestImages");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.RescueTeam", b =>
                {
                    b.Property<Guid>("RescueTeamID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RescueTeamID");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("City");

                    b.Property<double>("CurrentLatitude")
                        .HasColumnType("float")
                        .HasColumnName("CurrentLatitude");

                    b.Property<double>("CurrentLongitude")
                        .HasColumnType("float")
                        .HasColumnName("CurrentLongitude");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("CurrentStatus");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TeamName");

                    b.HasKey("RescueTeamID");

                    b.ToTable("RescueTeams");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.RescueTeamMember", b =>
                {
                    b.Property<Guid>("UserID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT")
                        .HasColumnName("IsDeleted");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("BIT")
                        .HasColumnName("IsLeader");

                    b.Property<Guid>("RescueTeamID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RescueTeamID");

                    b.HasKey("UserID");

                    b.HasIndex("RescueTeamID");

                    b.ToTable("RescueTeamMembers");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.Role", b =>
                {
                    b.Property<string>("RoleID")
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("RoleID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("RoleName");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = "AD",
                            IsDeleted = false,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = "RC",
                            IsDeleted = false,
                            RoleName = "Rescue Coordinator"
                        },
                        new
                        {
                            RoleID = "IM",
                            IsDeleted = false,
                            RoleName = "Inventory Manager"
                        },
                        new
                        {
                            RoleID = "RT",
                            IsDeleted = false,
                            RoleName = "Rescue Team Member"
                        });
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.User", b =>
                {
                    b.Property<Guid>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FullName");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("Phone");

                    b.Property<string>("RoleID")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("char(2)")
                        .HasColumnName("RoleID");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("Salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Username");

                    b.HasKey("UserID");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.Warehouse", b =>
                {
                    b.Property<int>("WarehouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WarehouseID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WarehouseID"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Address");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("BIT")
                        .HasColumnName("IsDeleted");

                    b.Property<double>("LocationLat")
                        .HasColumnType("float")
                        .HasColumnName("LocationLat");

                    b.Property<double>("LocationLong")
                        .HasColumnType("float")
                        .HasColumnName("LocationLong");

                    b.Property<Guid>("ManagerID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ManagerID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)'")
                        .HasColumnName("Name");

                    b.HasKey("WarehouseID");

                    b.HasIndex("ManagerID");

                    b.ToTable("Warehouses");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.CitizenNotification", b =>
                {
                    b.HasOne("FloodRescue.Repositories.Entites.RescueRequest", "RescueRequest")
                        .WithMany()
                        .HasForeignKey("RescueRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RescueRequest");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.IncidentReport", b =>
                {
                    b.HasOne("FloodRescue.Repositories.Entites.User", "Reported")
                        .WithMany()
                        .HasForeignKey("ReportedID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FloodRescue.Repositories.Entites.RescueMission", "RescueMission")
                        .WithMany()
                        .HasForeignKey("RescueMissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloodRescue.Repositories.Entites.User", "Resolver")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Reported");

                    b.Navigation("RescueMission");

                    b.Navigation("Resolver");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.Inventory", b =>
                {
                    b.HasOne("FloodRescue.Repositories.Entites.ReliefItem", "ReliefItem")
                        .WithMany()
                        .HasForeignKey("ReliefItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloodRescue.Repositories.Entites.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReliefItem");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.Notification", b =>
                {
                    b.HasOne("FloodRescue.Repositories.Entites.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.RefreshToken", b =>
                {
                    b.HasOne("FloodRescue.Repositories.Entites.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.ReliefItem", b =>
                {
                    b.HasOne("FloodRescue.Repositories.Entites.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.ReliefOrder", b =>
                {
                    b.HasOne("FloodRescue.Repositories.Entites.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FloodRescue.Repositories.Entites.RescueRequest", "RescueRequest")
                        .WithMany()
                        .HasForeignKey("RescueRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloodRescue.Repositories.Entites.RescueTeam", "RescueTeam")
                        .WithMany()
                        .HasForeignKey("RescueTeamID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FloodRescue.Repositories.Entites.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("RescueRequest");

                    b.Navigation("RescueTeam");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.ReliefOrderDetail", b =>
                {
                    b.HasOne("FloodRescue.Repositories.Entites.ReliefItem", "ReliefItem")
                        .WithMany()
                        .HasForeignKey("ReliefItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloodRescue.Repositories.Entites.ReliefOrder", "ReliefOrder")
                        .WithMany()
                        .HasForeignKey("ReliefOrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReliefItem");

                    b.Navigation("ReliefOrder");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.RescueMission", b =>
                {
                    b.HasOne("FloodRescue.Repositories.Entites.RescueRequest", "RescueRequest")
                        .WithMany()
                        .HasForeignKey("RescueRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloodRescue.Repositories.Entites.RescueTeam", "RescueTeam")
                        .WithMany()
                        .HasForeignKey("RescueTeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RescueRequest");

                    b.Navigation("RescueTeam");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.RescueRequest", b =>
                {
                    b.HasOne("FloodRescue.Repositories.Entites.User", "Coordinator")
                        .WithMany()
                        .HasForeignKey("CoordinatorID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Coordinator");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.RescueRequestImage", b =>
                {
                    b.HasOne("FloodRescue.Repositories.Entites.RescueRequest", "RescueRequest")
                        .WithMany()
                        .HasForeignKey("RescueRequestID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FloodRescue.Repositories.Entites.RescueTeam", null)
                        .WithMany("Images")
                        .HasForeignKey("RescueTeamID");

                    b.Navigation("RescueRequest");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.RescueTeamMember", b =>
                {
                    b.HasOne("FloodRescue.Repositories.Entites.RescueTeam", "RescueTeam")
                        .WithMany()
                        .HasForeignKey("RescueTeamID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FloodRescue.Repositories.Entites.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RescueTeam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.User", b =>
                {
                    b.HasOne("FloodRescue.Repositories.Entites.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.Warehouse", b =>
                {
                    b.HasOne("FloodRescue.Repositories.Entites.User", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.RescueTeam", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("FloodRescue.Repositories.Entites.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
